// frontend/javascript/frontend-javascript-vue/src/pages/LoginPage.vue
<script setup>
import { onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import Button from '../components/Button.vue';
import Panel from '../components/Panel.vue';
import PlaqueField from '../components/PlaqueField.vue';
import { LOGIN_MESSAGES } from '../lib/messages';
import {
  getToken,
  login,
  resolveAuthErrorMessage,
  saveSession,
  validateCredentials,
} from '../lib/auth';

const router = useRouter();
const username = ref('');
const password = ref('');
const error = ref('');
const submitting = ref(false);

onMounted(() => {
  if (getToken()) {
    void router.replace('/');
  }
});

async function handleSubmit(event) {
  event.preventDefault();
  error.value = '';

  const trimmedLogin = username.value.trim();
  const trimmedPassword = password.value.trim();
  const validationError = validateCredentials(trimmedLogin, trimmedPassword, LOGIN_MESSAGES);
  if (validationError) {
    error.value = validationError;
    return;
  }

  submitting.value = true;
  try {
    const response = await login(trimmedLogin, trimmedPassword);
    saveSession(response.token);
    await router.push(response.redirectUrl || '/');
  } catch (err) {
    error.value = resolveAuthErrorMessage(
      err,
      LOGIN_MESSAGES,
      LOGIN_MESSAGES.errorWrongCredentials,
    );
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <main class="auth-page">
    <Panel
      title="Login Form"
      title-test-id="login-form-title"
      test-id="login-panel"
      class-name="auth-panel"
    >
      <form id="login-form" class="auth-form" data-testid="login-form" @submit="handleSubmit">
        <div class="plaque-field-list">
          <PlaqueField
            v-model="username"
            label="Login"
            id="login-input"
            name="username"
            type="text"
            autocomplete="username"
            data-testid="login-input"
          />
          <PlaqueField
            v-model="password"
            label="Password"
            id="password-input"
            name="password"
            type="password"
            autocomplete="current-password"
            data-testid="password-input"
          />
        </div>

        <p id="error-message" class="auth-error" aria-live="polite" data-testid="error-message">
          {{ error }}
        </p>

        <div class="auth-form__actions">
          <Button
            id="submit-button"
            type="submit"
            variant="primary"
            block
            data-testid="submit-button"
            :disabled="submitting"
          >
            Login
          </Button>
        </div>
      </form>

      <p class="auth-footer-link">
        No account?
        <RouterLink to="/register" data-testid="register-link">Register</RouterLink>
      </p>
    </Panel>
  </main>
</template>

// frontend/typescript/frontend-typescript-react/src/pages/LoginPage.tsx
import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Button, Panel, PlaqueField } from '@zero-design-system/react';
import { LOGIN_MESSAGES } from '../lib/messages';
import {
  getToken,
  login,
  resolveAuthErrorMessage,
  saveSession,
  validateCredentials,
} from '../lib/auth';

export function LoginPage() {
  const navigate = useNavigate();
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (getToken()) {
      navigate('/', { replace: true });
    }
  }, [navigate]);

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setError('');

    const trimmedLogin = username.trim();
    const trimmedPassword = password.trim();
    const validationError = validateCredentials(trimmedLogin, trimmedPassword, LOGIN_MESSAGES);
    if (validationError) {
      setError(validationError);
      return;
    }

    setSubmitting(true);
    try {
      const response = await login(trimmedLogin, trimmedPassword);
      saveSession(response.token);
      navigate(response.redirectUrl || '/');
    } catch (err) {
      setError(
        resolveAuthErrorMessage(err, LOGIN_MESSAGES, LOGIN_MESSAGES.errorWrongCredentials ?? ''),
      );
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <main className="auth-page">
      <Panel
        title="Login Form"
        titleTestId="login-form-title"
        testId="login-panel"
        className="auth-panel"
      >
        <form id="login-form" className="auth-form" data-testid="login-form" onSubmit={handleSubmit}>
          <div className="plaque-field-list">
            <PlaqueField
              label="Login"
              id="login-input"
              name="username"
              type="text"
              autoComplete="username"
              data-testid="login-input"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
            />
            <PlaqueField
              label="Password"
              id="password-input"
              name="password"
              type="password"
              autoComplete="current-password"
              data-testid="password-input"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>

          <p id="error-message" className="auth-error" aria-live="polite" data-testid="error-message">
            {error}
          </p>

          <div className="auth-form__actions">
            <Button
              id="submit-button"
              type="submit"
              variant="primary"
              block
              data-testid="submit-button"
              disabled={submitting}
            >
              Login
            </Button>
          </div>
        </form>

        <p className="auth-footer-link">
          No account?{' '}
          <Link to="/register" data-testid="register-link">
            Register
          </Link>
        </p>
      </Panel>
    </main>
  );
}
