// frontend/_shared/frontend-react-ui/src/Button.tsx
import type { ButtonHTMLAttributes, ReactNode } from 'react';
import { cn } from './cn';
import './styles';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger';

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  block?: boolean;
  children: ReactNode;
}

const variantClass: Record<ButtonVariant, string> = {
  primary: 'btn--primary',
  secondary: 'btn--secondary',
  ghost: 'btn--ghost',
  danger: 'btn--danger',
};

export function Button({
  variant = 'primary',
  block = false,
  className,
  children,
  type = 'button',
  ...rest
}: ButtonProps) {
  return (
    <button
      type={type}
      className={cn('btn', variantClass[variant], block && 'btn--block', className)}
      {...rest}
    >
      {children}
    </button>
  );
}

// frontend/javascript/frontend-javascript-vue/src/components/Button.vue
<script setup>
defineProps({
  variant: { type: String, default: 'primary' },
  block: { type: Boolean, default: false },
  type: { type: String, default: 'button' },
  disabled: { type: Boolean, default: false },
  id: String,
});

const variantClass = {
  primary: 'btn--primary',
  secondary: 'btn--secondary',
  ghost: 'btn--ghost',
  danger: 'btn--danger',
};
</script>

<template>
  <button
    :id="id"
    :type="type"
    class="btn"
    :class="[variantClass[variant], block && 'btn--block']"
    :disabled="disabled"
  >
    <slot />
  </button>
</template>
