// frontend/typescript/frontend-typescript-vue/src/components/PlaqueField.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    label: string;
    id?: string;
    name?: string;
    type?: string;
    autocomplete?: string;
    modelValue?: string;
    labelVariant?: 'param' | 'caption';
    divided?: boolean;
    stretch?: boolean;
  }>(),
  {
    type: 'text',
    modelValue: '',
    labelVariant: 'caption',
    divided: true,
    stretch: true,
  },
);

const emit = defineEmits<{
  'update:modelValue': [value: string];
}>();

const attrs = useAttrs();

/** Autofill / DevTools: every form control needs id or name. */
const controlId = computed(() => props.id);
const controlName = computed(() => props.name ?? props.id);

const labelClass = (variant: 'param' | 'caption') =>
  variant === 'param' ? 'plaque-field__label' : 'plaque-field__text';
</script>

<template>
  <label
    class="plaque-field"
    :class="{
      'plaque-field--divided': divided,
      'plaque-field--stretch': stretch,
    }"
  >
    <span
      :class="labelClass(labelVariant)"
      :title="labelVariant === 'param' ? label : undefined"
    >
      {{ label }}
    </span>
    <span v-if="divided" class="plaque-divider" aria-hidden="true" />
    <input
      :id="controlId"
      :name="controlName"
      class="input plaque-field__control"
      :type="type"
      :autocomplete="autocomplete"
      :value="modelValue"
      v-bind="attrs"
      @input="emit('update:modelValue', ($event.target as HTMLInputElement).value)"
    />
  </label>
</template>

// frontend/javascript/frontend-javascript-angular/src/app/components/plaque-field.component.js
import { Component, EventEmitter } from '@angular/core';

/**
 * Label + control plaque. Host is the `<label>` (implicit control association,
 * and `plaque-field.css` targets `> .plaque-field__control` directly).
 *
 * `controlId` / `controlName` / `testId` rather than `id` / `name` / `data-testid`:
 * the plain attributes would land on the host `<label>`, but the reference markup
 * puts all three on the `<input>`. Call sites therefore bind literals (`[label]="'Login'"`)
 * — a static attribute matching an input is also reflected onto the host element.
 */
@Component({
  selector: 'label[app-plaque-field]',
  standalone: true,
  host: {
    class: 'plaque-field',
    '[class.plaque-field--divided]': 'divided',
    '[class.plaque-field--stretch]': 'stretch',
  },
  inputs: [
    'label',
    'controlId',
    'controlName',
    'type',
    'autocomplete',
    'value',
    'testId',
    'labelVariant',
    'divided',
    'stretch',
  ],
  outputs: ['valueChange'],
  template: `
    <span
      [class]="labelVariant === 'param' ? 'plaque-field__label' : 'plaque-field__text'"
      [attr.title]="labelVariant === 'param' ? label : null"
      >{{ label }}</span
    >
    @if (divided) {
      <span class="plaque-divider" aria-hidden="true"></span>
    }
    <input
      [id]="controlId"
      [attr.name]="controlName || controlId"
      class="input plaque-field__control"
      [type]="type"
      [attr.autocomplete]="autocomplete"
      [attr.data-testid]="testId"
      [value]="value"
      (input)="onInput($event)"
    />
  `,
})
export class PlaqueFieldComponent {
  label = '';
  controlId = undefined;
  controlName = undefined;
  type = 'text';
  autocomplete = undefined;
  value = '';
  testId = undefined;
  labelVariant = 'caption';
  divided = true;
  stretch = true;
  valueChange = new EventEmitter();

  onInput(event) {
    this.value = event.target.value;
    this.valueChange.emit(this.value);
  }
}
