// frontend/_shared/frontend-react-ui/src/Button.tsx
import type { ButtonHTMLAttributes, ReactNode } from 'react';
import { cn } from './cn';
import './styles';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger';

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  block?: boolean;
  children: ReactNode;
}

const variantClass: Record<ButtonVariant, string> = {
  primary: 'btn--primary',
  secondary: 'btn--secondary',
  ghost: 'btn--ghost',
  danger: 'btn--danger',
};

export function Button({
  variant = 'primary',
  block = false,
  className,
  children,
  type = 'button',
  ...rest
}: ButtonProps) {
  return (
    <button
      type={type}
      className={cn('btn', variantClass[variant], block && 'btn--block', className)}
      {...rest}
    >
      {children}
    </button>
  );
}

// frontend/typescript/frontend-typescript-vue/src/components/Button.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    variant?: 'primary' | 'secondary' | 'ghost' | 'danger';
    block?: boolean;
    type?: 'button' | 'submit' | 'reset';
    disabled?: boolean;
    id?: string;
  }>(),
  {
    variant: 'primary',
    block: false,
    type: 'button',
    disabled: false,
  },
);

const variantClass: Record<'primary' | 'secondary' | 'ghost' | 'danger', string> = {
  primary: 'btn--primary',
  secondary: 'btn--secondary',
  ghost: 'btn--ghost',
  danger: 'btn--danger',
};
</script>

<template>
  <button
    :id="id"
    :type="type"
    class="btn"
    :class="[variantClass[variant], block && 'btn--block']"
    :disabled="disabled"
  >
    <slot />
  </button>
</template>
