// frontend/_shared/frontend-react-ui/src/PlaqueField.tsx
import type { InputHTMLAttributes } from 'react';
import { cn } from './cn';
import { Input } from './Input';
import './styles';

export type PlaqueFieldLabelVariant = 'param' | 'caption';

export interface PlaqueFieldProps
  extends Omit<InputHTMLAttributes<HTMLInputElement>, 'className'> {
  label: string;
  className?: string;
  divided?: boolean;
  stretch?: boolean;
  /** `data-param-id` for wiring / e2e. */
  paramId?: string;
  /**
   * `param` → `.plaque-field__label` (configurator ids: `name`, `remoteUrl`).
   * `caption` → `.plaque-field__text` (auth human captions: Login / Password).
   */
  labelVariant?: PlaqueFieldLabelVariant;
}

/**
 * Divided plaque with a text `input` control. Canon:
 * - param id + input → `templates/plaque-field.html` `plaque-field-text`
 * - human caption + input → `plaque-field-caption-input`
 * Thin wrapper — label / divider / control slots stay SSOT in `plaque-field.css`.
 */
export function PlaqueField({
  label,
  className,
  divided = true,
  stretch = true,
  paramId,
  labelVariant = 'caption',
  id,
  name,
  ...inputProps
}: PlaqueFieldProps) {
  const labelClass =
    labelVariant === 'param' ? 'plaque-field__label' : 'plaque-field__text';
  // Autofill / DevTools: form controls need id or name. Prefer explicit props,
  // then configurator paramId (Capabilities / remote-hub).
  const controlId = id ?? paramId;
  const controlName = name ?? paramId ?? id;

  return (
    <label
      className={cn(
        'plaque-field',
        divided && 'plaque-field--divided',
        stretch && 'plaque-field--stretch',
        className,
      )}
      data-param-id={paramId}
    >
      <span className={labelClass} title={labelVariant === 'param' ? label : undefined}>
        {label}
      </span>
      {divided ? <span className="plaque-divider" aria-hidden="true" /> : null}
      <Input
        className="plaque-field__control"
        {...inputProps}
        id={controlId}
        name={controlName}
      />
    </label>
  );
}

// frontend/typescript/frontend-typescript-vue/src/components/PlaqueField.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    label: string;
    id?: string;
    name?: string;
    type?: string;
    autocomplete?: string;
    modelValue?: string;
    labelVariant?: 'param' | 'caption';
    divided?: boolean;
    stretch?: boolean;
  }>(),
  {
    type: 'text',
    modelValue: '',
    labelVariant: 'caption',
    divided: true,
    stretch: true,
  },
);

const emit = defineEmits<{
  'update:modelValue': [value: string];
}>();

const attrs = useAttrs();

/** Autofill / DevTools: every form control needs id or name. */
const controlId = computed(() => props.id);
const controlName = computed(() => props.name ?? props.id);

const labelClass = (variant: 'param' | 'caption') =>
  variant === 'param' ? 'plaque-field__label' : 'plaque-field__text';
</script>

<template>
  <label
    class="plaque-field"
    :class="{
      'plaque-field--divided': divided,
      'plaque-field--stretch': stretch,
    }"
  >
    <span
      :class="labelClass(labelVariant)"
      :title="labelVariant === 'param' ? label : undefined"
    >
      {{ label }}
    </span>
    <span v-if="divided" class="plaque-divider" aria-hidden="true" />
    <input
      :id="controlId"
      :name="controlName"
      class="input plaque-field__control"
      :type="type"
      :autocomplete="autocomplete"
      :value="modelValue"
      v-bind="attrs"
      @input="emit('update:modelValue', ($event.target as HTMLInputElement).value)"
    />
  </label>
</template>
