// frontend/javascript/frontend-javascript-vue/src/App.vue
<script setup>
import { computed, ref, watch } from 'vue';
import AppHeader from './components/AppHeader.vue';
import { useI18n } from './i18n';
import { appPath } from './lib/appBase';
import { buildHeaderConfig, syncHeaderNav } from './lib/headerConfig';

const { lang } = useI18n();
const headerConfig = computed(() => buildHeaderConfig(lang.value));
const navKey = ref(null);

watch(
  headerConfig,
  (config) => {
    navKey.value = syncHeaderNav(config, navKey.value);
  },
  { immediate: true },
);
</script>

<template>
  <AppHeader :config="headerConfig" :script-src="appPath('/js/header.js')" />
  <RouterView />
</template>

// frontend/javascript/frontend-javascript-react/src/App.jsx
import { AppHeader } from '@zero-design-system/react';
import { useEffect, useMemo, useRef } from 'react';
import { Outlet } from 'react-router-dom';
import { useI18n } from './i18n';
import { appPath } from './lib/appBase';
import { buildHeaderConfig, syncHeaderNav } from './lib/headerConfig';

export function App() {
  const { lang } = useI18n();
  const config = useMemo(() => buildHeaderConfig(lang), [lang]);
  const navKey = useRef(null);

  useEffect(() => {
    navKey.current = syncHeaderNav(config, navKey.current);
  }, [config]);

  return (
    <>
      <AppHeader config={config} scriptSrc={appPath('/js/header.js')} />
      <Outlet />
    </>
  );
}
