// frontend/javascript/frontend-javascript-react/src/App.jsx
import { AppHeader } from '@zero-design-system/react';
import { useEffect, useMemo, useRef } from 'react';
import { Outlet } from 'react-router-dom';
import { useI18n } from './i18n';
import { appPath } from './lib/appBase';
import { buildHeaderConfig, syncHeaderNav } from './lib/headerConfig';

export function App() {
  const { lang } = useI18n();
  const config = useMemo(() => buildHeaderConfig(lang), [lang]);
  const navKey = useRef(null);

  useEffect(() => {
    navKey.current = syncHeaderNav(config, navKey.current);
  }, [config]);

  return (
    <>
      <AppHeader config={config} scriptSrc={appPath('/js/header.js')} />
      <Outlet />
    </>
  );
}

// frontend/javascript/frontend-javascript-angular/src/app/app.component.js
import { Component, computed, effect } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { AppHeaderComponent } from './components/app-header.component.js';
import { useI18n } from './i18n/index.js';
import { appPath } from './lib/app-base.js';
import { buildHeaderConfig, syncHeaderNav } from './lib/header-config.js';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [AppHeaderComponent, RouterOutlet],
  template: `
    <app-header [config]="headerConfig()" [scriptSrc]="headerScriptSrc"></app-header>
    <router-outlet></router-outlet>
  `,
})
export class AppComponent {
  i18n = useI18n();
  headerScriptSrc = appPath('/js/header.js');
  headerConfig = computed(() => buildHeaderConfig(this.i18n.lang()));
  navKey = null;

  constructor() {
    effect(() => {
      this.navKey = syncHeaderNav(this.headerConfig(), this.navKey);
    });
  }
}
